name: Deploy
on:
  push:
    branches:
      - main
      - staging
      - development
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          echo "Dummy Workflow"
