name: Linter
on:
  pull_request:
    branches:
      - main
      - staging
      - development
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          echo "Dummy Workflow"
